version: '3.8'
services:
  app:
    container_name: app
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - docker_network
  db:
    container_name: db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    image: mongo:5.0.25
    command: mongod --port 27017
    volumes:
       - db-data:/data/db
    networks:
      - docker_network
  client:
    build: ./frontend
    container_name: client_frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app:ro
    stdin_open: true
    tty: true
    networks:
      - docker_network

volumes:
  db-data:
networks:
  docker_network:
