version: '3'
services:
  app:
    container_name: app
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - docker_network
  db:
    container_name: mongo_db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    image: mongo:5.0.25
    command: mongod --port ${MONGO_INITDB_PORT}
    ports:
      - ${MONGO_INITDB_PORT}:${MONGO_INITDB_PORT}
    volumes:
       - db-data:/data/db
    networks:
      - docker_network
  db_postgres:
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_INITDB_ROOT_USERNAME: ${POSTGRES_INITDB_ROOT_USERNAME}
      POSTGRES_INITDB_ROOT_PASSWORD: ${POSTGRES_INITDB_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_INITDB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_INITDB_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_INITDB_DB_NAME}
    image: postgres:latest
    ports:
      - ${POSTGRES_INITDB_PORT}:${POSTGRES_INITDB_PORT}
    volumes:
       - db-data-postgres:/data/db
    networks:
      - docker_network

volumes:
  db-data:
  db-data-postgres:
networks:
  docker_network:
