version: '3'
services:
  app:
    container_name: app
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - docker_network
  db:
    container_name: mongo_db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    image: mongo:5.0.25
    command: mongod --port ${MONGO_INITDB_PORT}
    ports:
      - ${MONGO_INITDB_PORT}:${MONGO_INITDB_PORT}
    volumes:
       - db-data:/data/db
    networks:
      - docker_network

volumes:
  db-data:
networks:
  docker_network:
